### ISSUE TITLE
Auto Close Not Closing

### ISSUE THREAD

**Issue by edpeeler** [aldeed/meteor-autoform-bs-datepicker#20] opened 2015-04-07 19:25 UTC
When selecting a date from a prior or subsequent month, the date picker widget does not close.  This issue does not occur when selecting a date from the current month.

**Comment by wuzhuzhu** [comment] 2015-04-14 01:03
In my case is all the same

**Comment by edpeeler** [comment] 2015-04-14 01:14
Were you using the latest version of meteor?  This behavior didn't manifest until I did the last update.  

Here is the template:  {{#autoForm collection="Wos" id="newWoa" type="insert"}}
  {{>hdr}}
    <fieldset>
      {{> afQuickField name="name"}}
      {{> afQuickField name="sdate" type="bootstrap-datepicker"}}
      {{> afQuickField name="woNum"}}
      {{> afQuickField name="make"}}
      {{> afQuickField name="model"}}
      {{> afQuickField name="snum"}}
      {{> afQuickField name="phone"}}
      {{> afQuickField name="tech"}}
      {{> afQuickField name="hrMeter"}}
      {{> afQuickField name="complaint" rows=5}}
    </fieldset>
  {{/autoForm}}

 Ed Peeler
San Francisco, CA

**Comment by joerodrig3** [comment] 2015-06-12 19:23
I have this issue as well with all datepicker inputs

**Comment by tbbooher** [comment] 2015-07-04 15:08
agreed, me too

**Comment by ravishhacker** [comment] 2015-07-13 20:42
It does work for me. I provided the autoclose option in the collection:
```
    deliverydate: {
        type: Date,
        label: 'Delivery Date',
        autoform: {
            afFieldInput: {
                type: "bootstrap-datepicker",
                "data-date-autoclose": "true"
            }
        }
    }
```
Autoclose works for any month but the orientation and other options are not working for me.

**Comment by Madsn** [comment] 2015-07-15 14:23
I have this issue as well. The fix suggested by @ravishhacker doesn't work for me. If I click a date, it closes correctly, but if I initially click anything other than a date, it won't close and I have to reload the page.

**Comment by frenchbread** [comment] 2016-02-19 11:11
Also had this issue, `"data-date-autoclose": "true"` option worked for me! Thanks @ravishhacker

**Comment by steven-tib** [comment] 2016-09-21 11:00
Having the same issue, the fix from @ravishhacker solves it partially only. As mentionned by @Madsn when we click somewhere else in the datepicker, e.g. the month at the top which zooms out to months view, then its impossible to close it without reloading the page. 

@frenchbread do you have this same behavior or is it working perfectly in all conditions for you ?

**Comment by frenchbread** [comment] 2016-09-21 11:10
@steven-tib Haven't tried it since then, but as I recall, I did not get it working in the end. The `"data-date-autoclose": "true"` setting worked for me once but then, even with this option set, datepicker didn't auto-close (like at all). Probably the issue was caused by using multiple fields with datepicker in the form IMHO. 

I ended up removing autoform and building form manually using [bootstrap-datepicker](https://eternicode.github.io/bootstrap-datepicker/?markup=input&format=&weekStart=&startDate=&endDate=&startView=0&minViewMode=0&maxViewMode=4&todayBtn=false&clearBtn=false&language=en&orientation=auto&multidate=&multidateSeparator=&keyboardNavigation=on&forceParse=on#sandbox)

**Comment by steven-tib** [comment] 2016-09-21 11:15
thanks @frenchbread for your quick reply, I guess I will try to find another solution then.

**Comment by aldeed** [comment] 2017-02-19 16:23
I don't see this issue in the latest version. Closing until someone can post an example app that reproduces the issue.

**Closed by aldeed** 2017-02-19 16:23 UTC
