### ISSUE TITLE
Infinite loop when using autosave

### ISSUE THREAD

**Issue by jfly** [aldeed/meteor-autoform-bs-datepicker#11] opened 2014-12-29 21:44 UTC
This is very similar to https://github.com/aldeed/meteor-autoform-bs-datetimepicker/issues/3.

**Comment by FatBoyXPC** [comment] 2015-01-27 08:35
Are there any updates on this? I would also like to take advantage of autosave and the datepicker!

**Comment by lynchem** [comment] 2016-01-26 18:11
+1 Very frustrating bug in an otherwise wonderful package

**Comment by aldeed** [comment] 2017-02-19 17:39
Fixed in latest

**Closed by aldeed** 2017-02-19 17:39 UTC

**Comment by mibcadet** [comment] 2017-03-05 08:58
Hi,

I'm using 1.2.0 version (due to lots of SimpleSchemas I would have to update to make collection2 2.0.0 compatible).
Is this fix also in 1.2.0? From my POV atm this loop issue with autosave still exists.

**Comment by aldeed** [comment] 2017-03-05 16:20
@mibcadet 1.2.0 and 2.0.0 are the same other than which version of autoform they depend on, so it should be fixed in both. If not, can you submit a new issue with some code that reproduces the issue you are seeing.
